name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        work-dir: ./
        buildozer-version: main
        
    - uses: actions/upload-artifact@v4
      with:
        name: isolines-app
        path: bin/*.apk
        retention-days: 7
